/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OgRouteImport } from './routes/og'
import { Route as LlmContextRouteImport } from './routes/llm-context'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnippetsIndexRouteImport } from './routes/snippets/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PhotographyIndexRouteImport } from './routes/photography/index'
import { Route as LabsIndexRouteImport } from './routes/labs/index'
import { Route as LabIndexRouteImport } from './routes/lab/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TagSlugRouteImport } from './routes/tag/$slug'
import { Route as SnippetsSplatRouteImport } from './routes/snippets/$'
import { Route as ProjectsSplatRouteImport } from './routes/projects/$'
import { Route as PortfolioSplatRouteImport } from './routes/portfolio/$'
import { Route as LabsSplatRouteImport } from './routes/labs/$'
import { Route as LabSlugRouteImport } from './routes/lab/$slug'
import { Route as ClientsSplatRouteImport } from './routes/clients/$'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as LabPrognosis2100IndexRouteImport } from './routes/lab/prognosis-2100/index'
import { Route as LabOnsLandIndexRouteImport } from './routes/lab/ons-land/index'
import { Route as LabGenArtGalleryIndexRouteImport } from './routes/lab/gen-art-gallery/index'
import { Route as LabCo2IndexRouteImport } from './routes/lab/co2/index'
import { Route as PhotographyPhotoSplatRouteImport } from './routes/photography/photo/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmContextRoute = LlmContextRouteImport.update({
  id: '/llm-context',
  path: '/llm-context',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsIndexRoute = SnippetsIndexRouteImport.update({
  id: '/snippets/',
  path: '/snippets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyIndexRoute = PhotographyIndexRouteImport.update({
  id: '/photography/',
  path: '/photography/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagSlugRoute = TagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SnippetsSplatRoute = SnippetsSplatRouteImport.update({
  id: '/snippets/$',
  path: '/snippets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSplatRoute = ProjectsSplatRouteImport.update({
  id: '/projects/$',
  path: '/projects/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSplatRoute = PortfolioSplatRouteImport.update({
  id: '/portfolio/$',
  path: '/portfolio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsSplatRoute = LabsSplatRouteImport.update({
  id: '/labs/$',
  path: '/labs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsSplatRoute = ClientsSplatRouteImport.update({
  id: '/clients/$',
  path: '/clients/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPrognosis2100IndexRoute = LabPrognosis2100IndexRouteImport.update({
  id: '/lab/prognosis-2100/',
  path: '/lab/prognosis-2100/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabOnsLandIndexRoute = LabOnsLandIndexRouteImport.update({
  id: '/lab/ons-land/',
  path: '/lab/ons-land/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabGenArtGalleryIndexRoute = LabGenArtGalleryIndexRouteImport.update({
  id: '/lab/gen-art-gallery/',
  path: '/lab/gen-art-gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabCo2IndexRoute = LabCo2IndexRouteImport.update({
  id: '/lab/co2/',
  path: '/lab/co2/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyPhotoSplatRoute = PhotographyPhotoSplatRouteImport.update({
  id: '/photography/photo/$',
  path: '/photography/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/health': typeof HealthRoute
  '/llm-context': typeof LlmContextRoute
  '/og': typeof OgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$': typeof BlogSplatRoute
  '/clients/$': typeof ClientsSplatRoute
  '/lab/$slug': typeof LabSlugRoute
  '/labs/$': typeof LabsSplatRoute
  '/portfolio/$': typeof PortfolioSplatRoute
  '/projects/$': typeof ProjectsSplatRoute
  '/snippets/$': typeof SnippetsSplatRoute
  '/tag/$slug': typeof TagSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/lab/': typeof LabIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/photography/': typeof PhotographyIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/photography/photo/$': typeof PhotographyPhotoSplatRoute
  '/lab/co2/': typeof LabCo2IndexRoute
  '/lab/gen-art-gallery/': typeof LabGenArtGalleryIndexRoute
  '/lab/ons-land/': typeof LabOnsLandIndexRoute
  '/lab/prognosis-2100/': typeof LabPrognosis2100IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/health': typeof HealthRoute
  '/llm-context': typeof LlmContextRoute
  '/og': typeof OgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$': typeof BlogSplatRoute
  '/clients/$': typeof ClientsSplatRoute
  '/lab/$slug': typeof LabSlugRoute
  '/labs/$': typeof LabsSplatRoute
  '/portfolio/$': typeof PortfolioSplatRoute
  '/projects/$': typeof ProjectsSplatRoute
  '/snippets/$': typeof SnippetsSplatRoute
  '/tag/$slug': typeof TagSlugRoute
  '/blog': typeof BlogIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/lab': typeof LabIndexRoute
  '/labs': typeof LabsIndexRoute
  '/photography': typeof PhotographyIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/snippets': typeof SnippetsIndexRoute
  '/photography/photo/$': typeof PhotographyPhotoSplatRoute
  '/lab/co2': typeof LabCo2IndexRoute
  '/lab/gen-art-gallery': typeof LabGenArtGalleryIndexRoute
  '/lab/ons-land': typeof LabOnsLandIndexRoute
  '/lab/prognosis-2100': typeof LabPrognosis2100IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/health': typeof HealthRoute
  '/llm-context': typeof LlmContextRoute
  '/og': typeof OgRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$': typeof BlogSplatRoute
  '/clients/$': typeof ClientsSplatRoute
  '/lab/$slug': typeof LabSlugRoute
  '/labs/$': typeof LabsSplatRoute
  '/portfolio/$': typeof PortfolioSplatRoute
  '/projects/$': typeof ProjectsSplatRoute
  '/snippets/$': typeof SnippetsSplatRoute
  '/tag/$slug': typeof TagSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/lab/': typeof LabIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/photography/': typeof PhotographyIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/snippets/': typeof SnippetsIndexRoute
  '/photography/photo/$': typeof PhotographyPhotoSplatRoute
  '/lab/co2/': typeof LabCo2IndexRoute
  '/lab/gen-art-gallery/': typeof LabGenArtGalleryIndexRoute
  '/lab/ons-land/': typeof LabOnsLandIndexRoute
  '/lab/prognosis-2100/': typeof LabPrognosis2100IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feed.xml'
    | '/health'
    | '/llm-context'
    | '/og'
    | '/sitemap.xml'
    | '/blog/$'
    | '/clients/$'
    | '/lab/$slug'
    | '/labs/$'
    | '/portfolio/$'
    | '/projects/$'
    | '/snippets/$'
    | '/tag/$slug'
    | '/blog/'
    | '/clients/'
    | '/lab/'
    | '/labs/'
    | '/photography/'
    | '/portfolio/'
    | '/projects/'
    | '/snippets/'
    | '/photography/photo/$'
    | '/lab/co2/'
    | '/lab/gen-art-gallery/'
    | '/lab/ons-land/'
    | '/lab/prognosis-2100/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feed.xml'
    | '/health'
    | '/llm-context'
    | '/og'
    | '/sitemap.xml'
    | '/blog/$'
    | '/clients/$'
    | '/lab/$slug'
    | '/labs/$'
    | '/portfolio/$'
    | '/projects/$'
    | '/snippets/$'
    | '/tag/$slug'
    | '/blog'
    | '/clients'
    | '/lab'
    | '/labs'
    | '/photography'
    | '/portfolio'
    | '/projects'
    | '/snippets'
    | '/photography/photo/$'
    | '/lab/co2'
    | '/lab/gen-art-gallery'
    | '/lab/ons-land'
    | '/lab/prognosis-2100'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/feed.xml'
    | '/health'
    | '/llm-context'
    | '/og'
    | '/sitemap.xml'
    | '/blog/$'
    | '/clients/$'
    | '/lab/$slug'
    | '/labs/$'
    | '/portfolio/$'
    | '/projects/$'
    | '/snippets/$'
    | '/tag/$slug'
    | '/blog/'
    | '/clients/'
    | '/lab/'
    | '/labs/'
    | '/photography/'
    | '/portfolio/'
    | '/projects/'
    | '/snippets/'
    | '/photography/photo/$'
    | '/lab/co2/'
    | '/lab/gen-art-gallery/'
    | '/lab/ons-land/'
    | '/lab/prognosis-2100/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  HealthRoute: typeof HealthRoute
  LlmContextRoute: typeof LlmContextRoute
  OgRoute: typeof OgRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSplatRoute: typeof BlogSplatRoute
  ClientsSplatRoute: typeof ClientsSplatRoute
  LabSlugRoute: typeof LabSlugRoute
  LabsSplatRoute: typeof LabsSplatRoute
  PortfolioSplatRoute: typeof PortfolioSplatRoute
  ProjectsSplatRoute: typeof ProjectsSplatRoute
  SnippetsSplatRoute: typeof SnippetsSplatRoute
  TagSlugRoute: typeof TagSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  LabsIndexRoute: typeof LabsIndexRoute
  PhotographyIndexRoute: typeof PhotographyIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SnippetsIndexRoute: typeof SnippetsIndexRoute
  PhotographyPhotoSplatRoute: typeof PhotographyPhotoSplatRoute
  LabCo2IndexRoute: typeof LabCo2IndexRoute
  LabGenArtGalleryIndexRoute: typeof LabGenArtGalleryIndexRoute
  LabOnsLandIndexRoute: typeof LabOnsLandIndexRoute
  LabPrognosis2100IndexRoute: typeof LabPrognosis2100IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-context': {
      id: '/llm-context'
      path: '/llm-context'
      fullPath: '/llm-context'
      preLoaderRoute: typeof LlmContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/': {
      id: '/snippets/'
      path: '/snippets'
      fullPath: '/snippets/'
      preLoaderRoute: typeof SnippetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/': {
      id: '/photography/'
      path: '/photography'
      fullPath: '/photography/'
      preLoaderRoute: typeof PhotographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$slug': {
      id: '/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof TagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snippets/$': {
      id: '/snippets/$'
      path: '/snippets/$'
      fullPath: '/snippets/$'
      preLoaderRoute: typeof SnippetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$': {
      id: '/projects/$'
      path: '/projects/$'
      fullPath: '/projects/$'
      preLoaderRoute: typeof ProjectsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$': {
      id: '/portfolio/$'
      path: '/portfolio/$'
      fullPath: '/portfolio/$'
      preLoaderRoute: typeof PortfolioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$': {
      id: '/labs/$'
      path: '/labs/$'
      fullPath: '/labs/$'
      preLoaderRoute: typeof LabsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$': {
      id: '/clients/$'
      path: '/clients/$'
      fullPath: '/clients/$'
      preLoaderRoute: typeof ClientsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/prognosis-2100/': {
      id: '/lab/prognosis-2100/'
      path: '/lab/prognosis-2100'
      fullPath: '/lab/prognosis-2100/'
      preLoaderRoute: typeof LabPrognosis2100IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/ons-land/': {
      id: '/lab/ons-land/'
      path: '/lab/ons-land'
      fullPath: '/lab/ons-land/'
      preLoaderRoute: typeof LabOnsLandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/gen-art-gallery/': {
      id: '/lab/gen-art-gallery/'
      path: '/lab/gen-art-gallery'
      fullPath: '/lab/gen-art-gallery/'
      preLoaderRoute: typeof LabGenArtGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/co2/': {
      id: '/lab/co2/'
      path: '/lab/co2'
      fullPath: '/lab/co2/'
      preLoaderRoute: typeof LabCo2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography/photo/$': {
      id: '/photography/photo/$'
      path: '/photography/photo/$'
      fullPath: '/photography/photo/$'
      preLoaderRoute: typeof PhotographyPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  HealthRoute: HealthRoute,
  LlmContextRoute: LlmContextRoute,
  OgRoute: OgRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSplatRoute: BlogSplatRoute,
  ClientsSplatRoute: ClientsSplatRoute,
  LabSlugRoute: LabSlugRoute,
  LabsSplatRoute: LabsSplatRoute,
  PortfolioSplatRoute: PortfolioSplatRoute,
  ProjectsSplatRoute: ProjectsSplatRoute,
  SnippetsSplatRoute: SnippetsSplatRoute,
  TagSlugRoute: TagSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  LabIndexRoute: LabIndexRoute,
  LabsIndexRoute: LabsIndexRoute,
  PhotographyIndexRoute: PhotographyIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SnippetsIndexRoute: SnippetsIndexRoute,
  PhotographyPhotoSplatRoute: PhotographyPhotoSplatRoute,
  LabCo2IndexRoute: LabCo2IndexRoute,
  LabGenArtGalleryIndexRoute: LabGenArtGalleryIndexRoute,
  LabOnsLandIndexRoute: LabOnsLandIndexRoute,
  LabPrognosis2100IndexRoute: LabPrognosis2100IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
